#!/usr/bin/env python3
#
# Build a pSConfig addresses section from a list of hosts on stdin
#

import json
import re
import sys

addresses = {}

input_data = json.load(sys.stdin)

for address, data in input_data.items():
    if address[0] == '#':
        continue

    addresses[address] = {
        'address': address,
        '_meta': {
            'display-name': data.get('label', address)
        }
    }

print(json.dumps(
    { 'addresses': addresses },
    sort_keys=True,
    indent=4,
    separators=(', ', ': ')))
