#!/usr/bin/python
#
# Determine if this tool can run a test based on a test spec.
#

import datetime
import sys

import pscheduler

json = pscheduler.json_load(exit_on_error=True);

# TODO: Should be checking the package schema and the task spec schema.
# TODO: Should be validating.

try:
    if json['type'] != 'rtt':
        pscheduler.fail('Unsupported test type')
except KeyError:
    pscheduler.fail('Missing test type')


spec = json['spec']

unsupported_options = [ 'flowlabel', 'hostnames', 'suppress-loopback', 'deadline' ]
for unsupported_option in unsupported_options:
    if spec.has_key(unsupported_option):
        pscheduler.fail("BWCTL does not support %s" % unsupported_option)

source = spec.get("source", "localhost")

if pscheduler.api_has_pscheduler(source):
    pscheduler.fail("Source has pscheduler, no need for BWCTL")

if not pscheduler.api_has_bwctl(source):
    pscheduler.fail("No BWCTL on %s" % source)

pscheduler.succeed()
