#!/usr/bin/python3
"""
Send results to the bit bucket
"""

import sys
import pscheduler

PARSER = pscheduler.RFC7464Parser(sys.stdin)
EMITTER = pscheduler.RFC7464Emitter(sys.stdout)

for parsed in PARSER:
    EMITTER({"succeeded": True})

pscheduler.succeed()
