#!/bin/sh

exec cat << EOF
{
    "name": "bitbucket",
    "description": "Dump results into the bit bucket.",
    "version": "0.0",

    "_": "This is a list of the tests the archiver understands how to handle.  If not provided, it is assumed the archiver will happily ingest anything it is handed.",
    "tests": [ "idle" ],

    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "info@perfsonar.net",
	"href": "http://www.perfsonar.net"
    }
}
EOF
