#!/bin/sh

exec cat << EOF
{
    "name": "bitbucket",
    "description": "Dump results into the bit bucket.",
    "version": "0.0",

    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "info@perfsonar.net",
	"href": "http://www.perfsonar.net"
    }
}
EOF

exit 0
