#!/usr/bin/env python3

#
# Development Order #7:
#
# Participant list generator for 'dhcp' task spec
#
# Input is an unvalidated test spec.
#
# Output is a list of hostnames or IPs that are participating.
#

import pscheduler
import sys

json = pscheduler.plugin_spec_is_valid('test', return_if_valid=True)

null_reason = None

#host only participant
host = json.get('host-node', json.get('host', None))
if host is None:
    null_reason = "No host specified"


participants = [ host ]

result = { "participants": participants }
if null_reason is not None:
    result["null-reason"] = null_reason

pscheduler.succeed_json(result)


