#!/bin/sh -e
#
# Build pScheduler enumerators from a skeleton and a validator schema.
#
# Usage: pscheduler-build-enumeration ENUM-JSON VALIDATOR-SCHEMA-JSON
#

TMPBASE=$(mktemp -d)
cleanup()
{
    rm -rf "${TMPBASE}"
}
trap cleanup EXIT


help()
{
    echo Usage: $(basename $0) ENUM-JSON VALIDATOR-SCHEMA-JSON
}


die()
{
    echo "$@" 1>&2
    exit 1
}


if [ "$#" -ne 2 ]
then
    help
    exit 1
fi


# Skeletal Enumeration
ENUM="${TMPBASE}/enum.json"
jq . "$1" > "${ENUM}" \
    || die "Could not process enumeration $1"


# Plugin validator array, converted to an object
VALIDATOR="${TMPBASE}/validator.json"
jq '[ to_entries[] | .key = (.key | tostring ) ] | from_entries' "$2" > "${VALIDATOR}" \
   || die "Could not process validator $2"


# pScheduler's internal dictionary
PS_DICT="${TMPBASE}/psdict.json"
pscheduler internal json-dictionary > "${PS_DICT}"


# Dereferenced validator
VALIDATOR_DEREF="${TMPBASE}/validator-deref.json"
jsonschematool --pretty --dereference "${PS_DICT}" "${VALIDATOR}" > "${VALIDATOR_DEREF}" \
    || die "Unable to process $2"


# Ibid, turned into an array
VALIDATOR_ARRAY="${TMPBASE}/validator-array.json"
jq '
      [ to_entries[] | .key = (.key | tonumber) ]
    | sort_by(.key)
    | [ .[] | .value ]
   ' "${VALIDATOR_DEREF}" \
       > "${VALIDATOR_ARRAY}"


# Generate the program
echo '#!/bin/sed -e 1d;/^#/d'
jq --slurp '
      .[0].spec = {}
    | .[0].spec.jsonschema = {}
    | .[0].spec.jsonschema.versions = .[1]
    | .[0]
    ' "${ENUM}" "${VALIDATOR_ARRAY}"
