#!/usr/bin/python
"""
Send a result to RabbitMQ.
"""

# Note that this imports the local copy, not what's installed on the
# system.
import pika

import datetime
import pscheduler
import sys



MAX_SCHEMA = 2

log_prefix="archiver-rabbitmq"

log = pscheduler.Log(prefix=log_prefix, quiet=True)



class PikaConnectionChannelPair:
    """
    This class implements a RabbitMQ connection and channel pair
    """

    def __init__(self, data):

        self.connection = pika.BlockingConnection(pika.URLParameters(data["_url"]))
        self.channel = self.connection.channel()
        self.exchange = data.get("exchange", "")
        self.routing_key = data.get("routing-key", "")


    def publish(self, message):

        self.channel.basic_publish(exchange=self.exchange,
                                   routing_key=self.routing_key,
                                   body=message)


    def __del__(self):

        self.channel.close()
        self.connection.close()




channels = pscheduler.ExpiringSet(
    creator=lambda key, data: PikaConnectionChannelPair(data),
    # No destroyer; __del__ will take care of it.
    purge_interval=datetime.timedelta(seconds=30),
    log=log
)



def archive(json):

    data = json["data"]

    schema = data.get("schema", 1)
    if schema > MAX_SCHEMA:
        return {
            "succeeded": False,
            "error": "Unsupported schema version %d; max is %d" % (
                schema, MAX_SCHEMA)
        }


    try:

        key = "%s```%s```%s" % (
            data["_url"],
            data.get("exchange", ""),
            data.get("routing-key", "")
        )

        lifetime = pscheduler.iso8601_as_timedelta(data.get("connection-lifetime","P0D"))

        channels(key, data, lifetime).publish(pscheduler.json_dump(json["result"]))

        result = {'succeeded': True}

    except Exception as ex:

        try:
            if ex.__module__ == "pika.exceptions":
                error = "Pika error: %s" % (ex.__class__.__name__)
            else:
                error = str(ex)
        except AttributeError:
            error = str(ex)

        result = {
            "succeeded": False,
            "error": error
        }

        if "retry-policy" in data:
            policy = pscheduler.RetryPolicy(data["retry-policy"], iso8601=True)
            retry_time = policy.retry(json["attempts"])
            if retry_time is not None:
                result["retry"] = retry_time

    return result



PARSER = pscheduler.RFC7464Parser(sys.stdin)
EMITTER = pscheduler.RFC7464Emitter(sys.stdout)

for parsed in PARSER:
    EMITTER(archive(parsed))

pscheduler.succeed()
