#!/bin/sh

exec cat << EOF
{
    "name": "rabbitmq",
    "description": "Send a JSON result to RabbitMQ",
    "version": "1.0",

    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "perfsonar-developer@internet2.edu",
	"href": "http://www.perfsonar.net"
    }
}
EOF
