#!/usr/bin/env python3
#
# Format a spec
#

import pscheduler

from validate import spec_is_valid
from validate import MAX_SCHEMA

TEMPLATE='''
{% if _mime_type == 'text/plain' %}

Host ........ {{ unspec(host) }}
Host Node ... {{ unspec(get('host-node')) }}
Network ..... {{ unspec(network) }}
Gateway ..... {{ unspec(gateway) }}
Scan Type ... {{ unspec(scan) }}
Limit ....... {{ unspec(limit) }}
Parallel .... {{ unspec(parallel) }}
Timeout ..... {{ unspec(timeout) }}

{% elif _mime_type == 'text/html' %}

<table>
<tr><td>Host</td><td>{{ unspec(host) }}</td></tr>
<tr><td>Host Node</td><td>{{ unspec(get('host-node')) }}</td></tr>
<tr><td>Network</td><td>{{ unspec(network) }}</td></tr>
<tr><td>Gateway</td><td>{{ unspec(gateway) }}</td></tr>
<tr><td>Scan Type</td><td>{{ unspec(scan) }}</td></tr>
<tr><td>Limit</td><td>{{ unspec(limit) }}</td></tr>
<tr><td>Parallel</td><td>{{ unspec(parallel) }}</td></tr>
<tr><td>Timeout</td><td>{{ unspec(timeout) }}</td></tr>
</table>

{% else %}

{{ error('Unsupported MIME type "' + _mime_type + '"') }}

{% endif %}
'''

pscheduler.spec_format_method(TEMPLATE, max_schema=MAX_SCHEMA, validator=spec_is_valid)
