#!/usr/bin/env python3
#
# Validator for any test spec
#

import ipaddress
import pscheduler

from validate import check_spec_semantics

pscheduler.plugin_spec_is_valid('test', semantic=check_spec_semantics)
