#!/usr/bin/env python3
#
# Convert a test specification to command-line options

import pscheduler

from validate import check_spec_semantics

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True, semantic=check_spec_semantics)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[
                                           # Strings
                                           ( 'host', 'host' ),
                                           ( 'host-node', 'host-node' ),
                                           ( 'network', 'network' ),
                                           ( 'gateway', 'gateway' ),
                                           ( 'limit', 'limit' ),
                                           ( 'parallel', 'parallel' ),
                                           ( 'scan', 'scan' ),
                                           ( 'timeout', 'timeout' ),
                                       ])


pscheduler.succeed_json(result)
