#!/bin/sh

exec cat << EOF
{
    "name": "simplestream",
    "description": "Simple TCP stream test - NOT FOR PRODUCTION",
    "version": "0.0",
    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "info@perfsonar.net",
	"href": "http://www.perfsonar.net"
    },
    "scheduling-class": "normal"
}
EOF
