#!/bin/sh

exec cat << EOF
{
    "name": "simplestream",
    "description": "Simple TCP stream test - NOT FOR PRODUCTION",
    "version": "1.0",
    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "perfsonar-developer@internet2.edu",
	"href": "http://www.perfsonar.net"
    },
    "scheduling-class": "background"
}
EOF
