#!/usr/bin/python
#
# Participant list generator for 'idle' task spec
#
# Input is a test spec, assumed to have been validated by spec-is-valid.
#
# Output is a list of hostnames or IPs that are participating.
#

import pscheduler
import sys

from validate import spec_is_valid


json = pscheduler.json_load(exit_on_error=True)

valid, message = spec_is_valid(json)

if not valid:
    pscheduler.fail(message)


try:
    source = json['source']
except KeyError:
    source = None

try:
    dest = json['dest']
except KeyError:
    pscheduler.fail('No dest in test specification')

pscheduler.succeed_json([ source, dest ])
