#!/usr/bin/env python3
#
# Convert a test specification to command-line options

import pscheduler

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[
        ( 'dest', 'dest' ),
        ( 'dest-node', 'dest-node' ),
        ( 'dawdle', 'dawdle' ),
        ( 'ip-version', 'ip-version' ),
        ( 'source', 'source' ),
        ( 'source-node', 'source-node' ),
        ( 'test-material', 'test-material' ),
        ( 'timeout', 'timeout' ),
        ( 'fail', 'fail' ),
        ( 'port', 'port' ),
        ])

pscheduler.succeed_json(result)


