#!/usr/bin/python
#
# Convert a test specification to command-line options

import pscheduler

from validate import spec_is_valid


spec = pscheduler.json_load(exit_on_error=True)

valid, message = spec_is_valid(spec)

if not valid:
    pscheduler.fail(message)

result = pscheduler.speccli_build_args(json, 
                                       strings=[
        ( 'receiver', 'receiver' ),
        ( 'dawdle', 'dawdle' ),
        ( 'test-material', 'test-material' ),
        ( 'timeout', 'timeout' ),
        ( 'fail', 'fail' ),
        ])

pscheduler.succeed_json(result)


