#!/usr/bin/env python3
"""
DESCRIPTION
"""

import sys
import pscheduler

MAX_SCHEMA = 1

def archive(json):
    """
    Archive the measurement
    """
    # Do whatever is necessary

    return {'succeeded': True}




# Read and streamed JSON and emit results

PARSER = pscheduler.RFC7464Parser(sys.stdin)
EMITTER = pscheduler.RFC7464Emitter(sys.stdout)

for parsed in PARSER:
    EMITTER(archive(parsed))

pscheduler.succeed()
