#!/usr/bin/env python3
#
# Format a spec
#

import jsontemplate
import pscheduler
import sys

from validate import spec_is_valid


try:
    format = sys.argv[1]
except IndexError:
    format = 'text/plain'

json = pscheduler.json_load(exit_on_error=True, max_schema=1)

valid, message = spec_is_valid(json)

if not valid:
    pscheduler.fail(message)


if format == 'text/plain':

    print('Data:')
    print(pscheduler.json_dump(json['data'])

elif format == 'text/html':

    print('<table border="0"><tr><td>Data</td><td><pre>')
    print(pscheduler.json_dump(json['data'])
    print('</pre></td></tr></table>')

else:

   pscheduler.fail("Unsupported format '%s'" % format)

pscheduler.succeed()
