#!/usr/bin/env python3
#
# Convert a test specification to command-line options

import pscheduler

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[
                                           ('data', 'data'),
                                           ('host', 'host'),
                                           ('host-node', 'host-node'),
                                       ])

pscheduler.succeed_json(result)
