#!/usr/bin/env python3
#Development Order #4:
import argparse
import pscheduler
import sys

input_args = []

if len(sys.argv) > 1:

   # Args are on the command line
   input_args = sys.argv[1:]

else:

   # Args are in a JSON array on stdin
   json_args = pscheduler.json_load(exit_on_error=True)
   input_args = []

   if not isinstance(json_args,list):
      pscheduler.fail("Invalid JSON for this operation")
   for arg in json_args:
      if not ( isinstance(arg, str)
               or isinstance(arg, int)
               or isinstance(arg, float) ):
         pscheduler.fail("Invalid JSON for this operation")
   input_args = [ str(arg) for arg in json_args ]



arg_parser = argparse.ArgumentParser(epilog=
"""Examples:
  task openports --network 192.0.2.0/24
    Scan for open ports on a network

  task openports --network 192.0.2.74 --lessinfo --timeout PT10S
    Scan a host and skip collecting OS information

  task openports --network 192.0.2.0/24 --ports 8080-8081
    Scan a range of ports on a network
""",
formatter_class=argparse.RawTextHelpFormatter
)

arg_parser.add_argument("--network",
                      help="Host(s) to scan (single host or CIDR notation for subnet)",
                      action="store", type="string",
                      dest="network")

arg_parser.add_argument("--ports",
                      help="Specify which port(s) to scan (ex: -p 1-1024,8080,65535).",
                      action="store", type="string",
                      dest="ports")

arg_parser.add_argument("--source",
                      help="Set source IP for nmap call. Not to be used with --source-node",
                      action="store", type="string",
                      dest="source")

arg_parser.add_argument("--source-node",
                      help="Set the source pScheduler node to make this call from. Not to be used with --source",
                      action="store", type="string",
                      dest="source_node")

arg_parser.add_argument("--timeout",
                      help="Maximum time to wait for responses.",
                      action="store", type="string",
                      dest="timeout")

# TODO: This is hidden from the CLI for the time being but is left enabled everywhere else.  #1223
#arg_parser.add_argument("--services",
#                      help="Scan for additional info beyond open ports.  (May run slower.)",
#                      action="store_true",
#                      dest="services")

args = arg_parser.parse_args(input_args)


result = { 'schema': 1 }

if args.network is not None:
   result['network'] = args.network

if args.ports is not None:
   result['ports'] = args.ports

if args.source is not None:
   result['source'] = args.source

if args.source_node is not None:
   result['source_node'] = args.source_node
if args.timeout is not None:
   result['timeout'] = args.timeout

# TODO: Hidden until service detection problems are resolved.  #1223
#if options.services is not None:
#   result['services'] = options.services


pscheduler.succeed_json(result)
