#!/usr/bin/env python3
#Development Order #4:
import optparse
import pscheduler
import sys

if len(sys.argv) > 1:

   # Args are on the command line
   args = sys.argv[1:]

else:

   # Args are in a JSON array on stdin
   json_args = pscheduler.json_load(exit_on_error=True)
   args = []

   if not isinstance(json_args,list):
      pscheduler.fail("Invalid JSON for this operation")
   for arg in json_args:
      if not ( isinstance(arg, str)
               or isinstance(arg, int)
               or isinstance(arg, float) ):
         pscheduler.fail("Invalid JSON for this operation")
   args = [ str(arg) for arg in json_args ]



opt_parser = pscheduler.FailingOptionParser(epilog=
"""Examples:
  task openports --network 192.0.2.0/24
    Scan for open ports on a network

  task openports --network 192.0.2.74 --lessinfo --timeout PT10S
    Scan a host and skip collecting OS information

  task openports --network 192.0.2.0/24 --ports 8080-8081
    Scan a range of ports on a network
"""
)

opt_parser.add_option("--network",
                      help="Host(s) to scan (single host or CIDR notation for subnet)",
                      action="store", type="string",
                      dest="network")

opt_parser.add_option("--ports",
                      help="Specify which port(s) to scan (ex: -p 1-1024,8080,65535).",
                      action="store", type="string",
                      dest="ports")

opt_parser.add_option("--source",
                      help="Set source IP for nmap call. Not to be used with --source-node",
                      action="store", type="string",
                      dest="source")

opt_parser.add_option("--source-node",
                      help="Set the source pScheduler node to make this call from. Not to be used with --source",
                      action="store", type="string",
                      dest="source_node")

opt_parser.add_option("--timeout",
                      help="Maximum time to wait for responses.",
                      action="store", type="string",
                      dest="timeout")

# TODO: This is hidden from the CLI for the time being but is left enabled everywhere else.  #1223
#opt_parser.add_option("--services",
#                      help="Scan for additional info beyond open ports.  (May run slower.)",
#                      action="store_true",
#                      dest="services")

(options, remaining_args) = opt_parser.parse_args(args)


""" if len(remaining_args) != 0:
   pscheduler.fail("Unusable arguments: %s" % " ".join(remaining_args)) """

result = { 'schema': 1 }

if options.network is not None:
   result['network'] = options.network

if options.ports is not None:
   result['ports'] = options.ports

if options.source is not None:
   result['source'] = options.source

if options.source_node is not None:
   result['source_node'] = options.source_node
if options.timeout is not None:
   result['timeout'] = options.timeout

# TODO: Hidden until service detection problems are resolved.  #1223
#if options.services is not None:
#   result['services'] = options.services


pscheduler.succeed_json(result)
