#!/usr/bin/env python3
#
# Validator for 'openports' test spec
#

import pscheduler

def check_semantics(proposed):
    '''
    This checks that the spec is semantically-valid.  It is safe to
    assume that validation of the JSON passed.
    '''

    # TODO: This is untested.

    #Verify Port Order is valid
    if proposed.get("ports") is None:
        return(True, 'OK')

    portlist = proposed.get("ports").split(",")
    allports = []
    for ele in portlist:
        begin = end = ele
        if "-" in ele:
            (begin, end) = ele.split("-")
            if int(end) < int(begin):
                pscheduler.succeed_json({
                    "valid": False,
                    "error": "Port range is backwards. Did you mean " + end + "-" + begin +"?"
                })
        for port in range(int(begin), int(end)+1):
            newports = []
            if port in allports:
                pscheduler.succeed_json({
                "valid": False,
                "error": "Duplicate value in port list: " + str(port)
                })
            newports.append(port)
        allports+=newports


pscheduler.plugin_spec_is_valid('test', semantic=check_semantics)

