#!/usr/bin/env python3

#
# Development Order #5:
# 
# This file will convert a test specification to command-line options.
#
# This can be tested directly using the following syntax:
# ./cli-to-spec --option argument | ./spec-to-cli

import pscheduler

from validate import check_spec_semantics

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True, semantics=check_spec_semantics)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[

        # Add all argument strings here, as tuples

        ( 'network', 'network' ),
        ( 'ports', 'ports' ),
        ( 'timeout', 'timeout' ),
        ( 'source', 'source' ),
        ( 'source_node', 'source_node' ),
        # TODO: Disabled until we figure out timings.  #1223
        #( 'services', 'services'),
        ])

pscheduler.succeed_json(result)
