#!/bin/sh

set -e

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/config.pgsql ]; then
    . /usr/share/dbconfig-common/dpkg/config.pgsql

    dbc_dbuser=pscheduler
    dbc_dbname=pscheduler
    dbc_authmethod_user=password
    dbc_go pscheduler-server $@
fi
