#!/usr/bin/python
#
# Determine if this tool can run a test based on a test spec.
#

import datetime
import sys

import pscheduler

json = pscheduler.json_load();

# TODO: Should be checking the package schema and the task spec schema.
# TODO: Should be validating.

try:
    if json['type'] != 'simplestream':
        pscheduler.fail('Unsupported test type')
except KeyError:
    pscheduler.fail('Missing test type')


# Require that the timeout be at least twice the dawdle interval.

try:
    timeout = pscheduler.iso8601_as_timedelta(json['spec']['timeout'])
except KeyError:
    pscheduler.fail("Missing or invalid timeout.")

try:
    dawdle = pscheduler.iso8601_as_timedelta(json['spec']['dawdle'])
except KeyError:
    dawdle = pscheduler.iso8601_as_timedelta('P0')

if dawdle * 2 > timeout:
    pscheduler.fail("Dawdle duration must be less than half the timeout.")


pscheduler.succeed()
