#!/usr/bin/env python3
#
# Convert a test specification to command-line options
#

import pscheduler

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[
                                           ( 'source', 'source' ),
                                           ( 'source-node', 'source-node' ),
                                           ( 'dest', 'dest' ),
                                           ( 'timeout', 'timeout' ),
                                       ]
                                   )


pscheduler.succeed_json(result)
