#!/usr/bin/env python3
#
# Format a spec
#

import jsontemplate
import pscheduler
import sys

from validate import spec_is_valid


try:
   format = sys.argv[1]
except IndexError:
   format = 'text/plain'


json = pscheduler.json_load(exit_on_error=True)

valid, message = spec_is_valid(json)

if not valid:
    pscheduler.fail(message)

if format == 'text/plain':

    template = """
Source ...................... {.section source}{source}{.or}Not Specified{.end}
Source Node ................. {.section source-node}{source_node}{.or}Not Specified{.end}
Timeout ................... {.section timeout}{timeout}{.or}Not Specified{.end}
Dest................. {.section dest}{dest}{.or}Not Specified{.end}
""" % ("True", "True")

elif format == 'text/html':

   template = """
<table>
<tr><td>Host</td><td>{.section source}{source}{.or}Not Specified{.end}</td></tr>
<tr><td>Source Node</td><td>{.section source-node}{source_node}{.or}Not Specified{.end}</td></tr>
<tr><td>Timeout</td><td>{.section timeout}{timeout}{.or}Not Specified{.end}</td></tr>
<tr><td>Dest</td><td>{.section dest}{dest}{.or}Not Specified{.end}</td></tr>
</table>
""" % ("True", "True")
else:

   pscheduler.fail("Unsupported format '%s'" % format)


# TODO: Should probably handle exceptions in a nicer way.
print(jsontemplate.expand(template, json).strip())
