#!/usr/bin/env python3
#
# Convert comamnd-line options to a test specification
#

import argparse
import pscheduler
import sys

if len(sys.argv) > 1:

   # Args are on the command line
   args = sys.argv[1:]

else:

   # Args are in a JSON array on stdin
   json_args = pscheduler.json_load(exit_on_error=True)
   args = []

   if not isinstance(json_args,list):
      pscheduler.fail("Invalid JSON for this operation")
   for arg in json_args:
      if not ( isinstance(arg, str)
               or isinstance(arg, int)
               or isinstance(arg, float) ):
         pscheduler.fail("Invalid JSON for this operation")
   args = [ str(arg) for arg in json_args ]



# Gargle the arguments

arg_parser = argparse.ArgumentParser(epilog=
"""Examples:

  task rtt --dest ps.example.com
      Measure round trip time from here to ps.example.com

  task rtt --source ps2.example.org --dest ps.example.com
      Measure round trip time from ps2.example.org to www.example.com

  task rtt --length 512 --dest ps.example.com
      Use 512-byte packets

  task rtt --ttl 12 --dest ps.example.com
      Limit time to live to 12 hops
""",
    formatter_class=argparse.RawTextHelpFormatter)


arg_parser.add_argument("-c","--count",
                      help="Test count",
                      action="store", type=int,
                      dest="count")

arg_parser.add_argument("-d","--dest",
                      help="Destination host",
                      action="store", type=str,
                      dest="dest")

arg_parser.add_argument("--flow-label",
                      help="Flow label",
                      action="store", type=int,
                      dest="flow_label")

arg_parser.add_argument("--fragment",
                      help="Allow packet fragmentation",
                      default=None,
                      action="store_true",
                      dest="fragment")
arg_parser.add_argument("--no-fragment",
                      help="Don't allow packet fragmentation",
                      action="store_false",
                      dest="fragment")

arg_parser.add_argument("--hostnames",
                      help="Look up hostnames from IPs",
                      default=None,
                      action="store_true",
                      dest="hostnames")
arg_parser.add_argument("--no-hostnames",
                      help="Don't look up hostnames from IPs",
                      action="store_false",
                      dest="hostnames")

arg_parser.add_argument("-i","--interval",
                      help="Time to wait between packets sent",
                      action="store", type=str,
                      dest="interval")

arg_parser.add_argument("--ip-version",
                      help="IP version to use",
                      action="store", type=int,
                      dest="ip_version")

arg_parser.add_argument("-s","--source",
                      help="Source address or interface",
                      action="store", type=str,
                      dest="source")

arg_parser.add_argument("--source-node",
                      help="Source pScheduler node, if different",
                      action="store", type=str,
                      dest="source_node")

arg_parser.add_argument("--suppress-loopback",
                      help="Suppress multicast loopback",
                      default=None,
                      action="store_true",
                      dest="suppress_loopback")
arg_parser.add_argument("--no-suppress-loopback",
                      help="Don't suppress multicast loopback",
                      action="store_false",
                      dest="suppress_loopback")

arg_parser.add_argument("--ip-tos",
                      help="IP type-of-service octet (integer)",
                      action="store", type=int,
                      dest="ip_tos")

arg_parser.add_argument("--length",
                      help="Packet length",
                      action="store", type=int,
                      dest="length")

arg_parser.add_argument("--ttl",
                      help="Time to live",
                      action="store", type=int,
                      dest="ttl")

arg_parser.add_argument("--deadline",
                      help="Deadline for all measurements to complete",
                      action="store", type=str,
                      dest="deadline")

arg_parser.add_argument("--timeout",
                      help="Timeout for each round trip",
                      action="store", type=str,
                      dest="timeout")

arg_parser.add_argument("--protocol",
                      help="Protocol used to measure round trip time",
                      action="store", type=str,
                      dest="protocol")


args = arg_parser.parse_args(args)

result = { }
schema = pscheduler.HighInteger(1)


if args.count is not None:
   result['count'] = args.count

if args.dest is not None:
   result['dest'] = args.dest

if args.flow_label is not None:
   result['flow-label'] = args.flow_label

if args.fragment is not None:
   result['fragment'] = args.fragment
   schema.set(3)

if args.hostnames is not None:
   result['hostnames'] = args.hostnames

if args.interval is not None:
   result['interval'] = args.interval

if args.ip_version is not None:
   result['ip-version'] = args.ip_version

if args.source is not None:
   result['source'] = args.source

if args.source_node is not None:
   result['source-node'] = args.source_node

if args.suppress_loopback is not None:
   result['suppress-loopback'] = args.suppress_loopback

if args.ip_tos is not None:
   result['ip-tos'] = args.ip_tos

if args.length is not None:
   result['length'] = args.length

if args.ttl is not None:
   result['ttl'] = args.ttl

if args.deadline is not None:
   result['deadline'] = args.deadline

if args.timeout is not None:
   result['timeout'] = args.timeout

if args.protocol is not None:
   result['protocol'] = args.protocol
   schema.set(2)

result["schema"] = schema.value()

pscheduler.succeed_json(result)
