#!/bin/sh

exec cat << EOF
{
    "name": "rtt",
    "description": "Measure the round trip time between hosts",
    "version": "0.0",
    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "info@perfsonar.net",
	"href": "http://www.perfsonar.net"
    }
}
EOF
