#!/usr/bin/python
#
# Participant list generator for 'rtt' test spec
#

import pscheduler
import sys

from validate import spec_is_valid

json = pscheduler.json_load(exit_on_error=True)

valid, message = spec_is_valid(json)

if not valid:
    pscheduler.fail(message)

# There's only ever one participant, and that's us.
pscheduler.succeed_json([None])
