#!/usr/bin/python
#
# Convert a test specification to command-line options

import pscheduler

from validate import spec_is_valid

spec = pscheduler.json_load(exit_on_error=True)

valid, message = spec_is_valid(spec)

if not valid:
    pscheduler.fail(message)


result = pscheduler.speccli_build_args(spec, 
                                       strings=[
        # Strings
        ( 'count', 'count' ),
        ( 'dest', 'dest' ),
        ( 'flowlabel', 'flowlabel' ),
        ( 'interval', 'interval' ),
        ( 'ip-version', 'ip-version' ),
        ( 'source', 'source' ),
        ( 'source-node', 'source-node' ),
        ( 'tos', 'tos' ),
        ( 'length', 'length' ),
        ( 'ttl', 'ttl' ),
        ( 'deadline', 'deadline' ),
        ( 'timeout', 'timeout' ),
        ],
                                       bools=[
        ( 'suppress-loopback', 'suppress-loopback' ),
        ( 'hostnames', 'hostnames' ),
        ])


pscheduler.succeed_json(result)
