#!/bin/sh -e
#
# Build pScheduler as a Docker container and push it
#

OPT_PUSH=true
OPT_BUILD=stable

while echo "$1" | egrep -qe '^--.'
do
  OPTION="$1"
  shift

  case "$OPTION" in

      --push)
          OPT_PUSH=true
          ;;
      --no-push)
          OPT_PUSH=false
          ;;

      --build)
	  OPT_BUILD="$1"
	  shift
	  ;;

      *)
          echo "Unknown option $OPTION" 1>&2
	  exit 1
          ;;


  esac
done



$OPT_PUSH && docker login

curl -s -O https://raw.githubusercontent.com/perfsonar/pscheduler/master/scripts/docker/Dockerfile
TIMESTAMP=$(date +%Y%m%d%H%M%S)
docker build \
    --no-cache \
    --build-arg "BUILD_NAME=${OPT_BUILD}" \
    -t "perfsonar/pscheduler-demo:${TIMESTAMP}" \
    .

$OPT_PUSH && docker tag "perfsonar/pscheduler-demo:${TIMESTAMP}" perfsonar/pscheduler-demo:latest
$OPT_PUSH && docker push "perfsonar/pscheduler-demo:${TIMESTAMP}"
$OPT_PUSH && docker push perfsonar/pscheduler-demo:latest

rm -f Dockerfile
