#!/usr/bin/env python3
#
# random-string - Generate random, printable strings.
#

import argparse
import random
import string


# Gargle the arguments

arg_parser = argparse.ArgumentParser()
arg_parser.add_argument("-l", "--length",
                      help="Length of string produced",
                      action="store", type=int, dest="length",
                      default=32)

arg_parser.add_argument("-r", "--randlength",
                      help="Randomize the string length",
                      action="store_true", dest="randlength")

arg_parser.add_argument("-s", "--safe",
                      help="Produce a conservative, non-confusing string",
                      action="store_true", dest="safe")

args = arg_parser.parse_args()

if args.length < 1:
    arg_parser.error('Length must be greater than zero.')
    exit(1)


#
# Main Program
#

random.seed()

remaining = args.length
if args.randlength:
    half = int(remaining/2)
    remaining = half + int(random.random() * half)


charset = string.digits + string.ascii_letters
if not args.safe:
    charset += string.punctuation
charset_len = len(charset)


string = ""

while remaining:
    string += charset[int((random.random() * charset_len))]
    remaining -= 1

print(string)
