.\" random-string man page
.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.de Id
.ds Dt \\$4
..
.TH RANDOM-STRING 1
.SH NAME
random-string \- Generate random strings of printable text
.SH SYNOPSIS
.B random-string
.I [ OPTIONS ]

.SH DESCRIPTION
.PP
This program generates strings of printable text suitable for use as
passwords.

.SH OPTIONS
.TP
.BI -l\ length
Produce a string
.I length
characters long.  The default is 32.

.TP
.BI -r
Randomize the length of the string to anywhere between half and all of
the specified length.


.TP
.BI -s
Produce a safe string consisting only of letters and digits.
