#!/bin/sh

exec cat << EOF
{
    "name": "owdelay",
    "description": "Tests designed primarily to measure one-way network delay and associated metrics",
    "version": "0.0",
    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "perfsonar-developer@perfsonar.net",
	"href": "http://www.perfsonar.net"
    }
}
EOF
