#!/usr/bin/python
#
# Convert a test specification to command-line options

import pscheduler

from validate import spec_is_valid

spec = pscheduler.json_load(exit_on_error=True)

valid, message = spec_is_valid(spec)

if not valid:
    pscheduler.fail(message)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[

        # Add all argument strings here, as tuples
        # For example:

        ( 'example', 'example' ),
        ( 'example2', 'example2'),
        ])

pscheduler.succeed_json(result)
