#!/bin/sh -e

# Make sure ping can send raw packets without being root.

PING=$(type ping | sed -e 's/.*\s\+//')

if [ -x "${PING}" ]
then
    setcap cap_net_raw+p "${PING}"
else
    echo "Can't find executable ping '${PING}'"
    exit 1
fi
