#!/usr/bin/env python3
#
# Validator for 'wifibssid' test limit spec
#

import pscheduler

pscheduler.succeed_json({
    "valid": False,
    "error": "Test limit specifications are no longer supported."
})
