#!/usr/bin/env python3

#
# Development Order #4:
# 
# This file encodes CLI arguments as JSON data in a test spec,
# as defined by the datatypes in validate.py
# 
# This can be tested directly using the following syntax:
# ./cli-to-spec --option argument
#

import re
import optparse
import pscheduler
import sys

if len(sys.argv) > 1:

   # Args are on the command line
   args = sys.argv[1:]

else:

   # Args are in a JSON array on stdin
   json_args = pscheduler.json_load(exit_on_error=True)
   args = []

   if not isinstance(json_args,list):
      pscheduler.fail("Invalid JSON for this operation")
   for arg in json_args:
      if not ( isinstance(arg, str)
               or isinstance(arg, int)
               or isinstance(arg, float) ):
         pscheduler.fail("Invalid JSON for this operation")
   args = [ str(arg) for arg in json_args ]



# Gargle the arguments

opt_parser = pscheduler.FailingOptionParser(epilog=
"""
    This text will be printed out at the bottom of the
    "help" message. Change this to whatever you like,
    or don't include it at all. This could be a good place
    for example usage cases, etc.
"""
)

# Add all potential command line options here
# Check https://docs.python.org/3/library/optparse.html for more
# documentation on the opt parser


opt_parser.add_option("--source",
                      help="Sending host",
                      action="store", type="string",
                      dest="source")

opt_parser.add_option("--source-node",
                      help="pScheduler node on sending host, if different",
                      action="store", type="string",
                      dest="source_node")

opt_parser.add_option("--dest",
                      help="Receiving host",
                      action="store", type="string",
                      dest="dest")

opt_parser.add_option("--timeout",
                      help="Timeout for each ping, in milliseconds",
                      action="store", type="int",
                      dest="timeout")

(options, remaining_args) = opt_parser.parse_args(args)

result = { 'schema': 1 }

if options.source is not None:
   result['source'] = options.source

if options.source_node is not None:
   result['source-node'] = options.source_node

if options.dest is not None:
   result['dest'] = options.dest

if options.timeout is not None:
   result['timeout'] = options.timeout

pscheduler.succeed_json(result)
