#!/usr/bin/env python3

#
# Development Order #5:
# 
# This file will convert a test specification to command-line options.
#
# This can be tested directly using the following syntax:
# ./cli-to-spec --option argument | ./spec-to-cli

import pscheduler

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[

        # Add all argument strings here, as tuples

        ( 'source', 'source' ),
        ( 'source-node', 'source-node' ),
        ( 'dest', 'dest' ),
        ( 'port', 'port' ),
        ( 'ip-version', 'ip-version' ),
        ])

pscheduler.succeed_json(result)
