#!/bin/sh -e
#
# Dump the daemon threads
#

[ -t 1 ] && LONG= || LONG=l

[ $# -eq 0 ] &&  LIST='scheduler runner archiver ticker' || LIST=$@

for SERVICE in ${LIST}
do
    PID=$(systemctl show --property MainPID --value "pscheduler-${SERVICE}")
    pstree -ap${LONG} "${PID}"
    echo
done
