#!/usr/bin/python
#
# Fail at archiving most of the time.
#

import pscheduler
import random
import sys

random.seed()

if random.random() > 0.8:
    json = {
        "succeeded": True
        }
else:
    if random.random() > 0.5:
        json = {
            "succeeded": False,
            "error": "Induced random failure with retry",
            "retry": "PT10S"
            }
    else:
        json = {
            "succeeded": False,
            "error": "Induced random failure, not retrying",
            }

pscheduler.succeed_json(json)
