#!/usr/bin/env python3
#
# Validate data for the failer archiver
#

import pscheduler

try:
    json = pscheduler.json_load(max_schema=2)
except ValueError as ex:
    pscheduler.succeed_json({
        "valid": False,
        "error": str(ex)
        })

data_validator = {

    "local": {

        "FailerArchiveSpecification_V1": {
            "type": "object",
            "properties": {
                "schema": {" type": "integer", "enum": [ 1 ] },
                "delay": { "$ref": "#/pScheduler/Duration" },
                "fail": { "$ref": "#/pScheduler/Float" },
                "retry": { "$ref": "#/pScheduler/Float" }
            },
            "additionalProperties": False
        },

        "FailerArchiveSpecification_V2": {
            "type": "object",
            "properties": {
                "schema": {" type": "integer", "enum": [ 2 ] },
                "schema": { "$ref": "#/pScheduler/Cardinal" },
                "delay": { "$ref": "#/pScheduler/Duration" },
                "fail": { "$ref": "#/pScheduler/Float" },
                "retry": { "$ref": "#/pScheduler/Float" },
                "badly": { "$ref": "#/pScheduler/Boolean" }
            },
            "required": [
                "schema"
            ],
            "additionalProperties": False
        },

        "FailerArchiveSpecification": {
            "anyOf": [
                { "$ref": "#/local/FailerArchiveSpecification_V1" },
                { "$ref": "#/local/FailerArchiveSpecification_V2" }
            ]
        }
    },

    "$ref": "#/local/FailerArchiveSpecification"

}

valid, error = pscheduler.json_validate(json, data_validator)

if not valid:
    pscheduler.succeed_json({
        "valid": False,
        "error": error
        })
    
pscheduler.succeed_json({ "valid": True })
