.\" jsonschematool man page
.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.de Id
.ds Dt \\$4
..
.TH JSONSCHEMATOOL 1
.SH NAME
jsonschematool \- Merge and dereference JSON Schema documents
.SH SYNOPSIS
.B jsonschematool
.I [ OPTIONS ]
.I INPUT
.I [ INPUT ... ]

.SH DESCRIPTION
.PP

This program combines JSONSchama 

TODO: Finish this.

.SH ARGUMENTS

.IR XXX
Xxx

.SH OPTIONS
.TP
.BI --foo\ FOO
Foo some
.I BAR
before baz.
