.\" jsonschematool man page
.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.de Id
.ds Dt \\$4
..
.TH JSONSCHEMATOOL 1
.SH NAME
jsonschematool \- Merge and dereference JSON Schema documents
.SH SYNOPSIS
.B jsonschematool
.I [ OPTIONS ]
.I [ INPUT ... ]

.SH DESCRIPTION
.PP

This program combines JSONSchema files and, optionally, replaces
references with their actual definitions.

.SH ARGUMENTS

Each
.I INPUT
argument to the program is the path to a JSON file containing a
full or partial JSON Schema documents.  The path
.I -
may be used once to signify the standard input.  If no arguments are
provided, the program will read one input file from the standard
input.

Inputs should be provided in "dependency order," meaning that files
containing referenced definitions should be placed before those that
reference them.


.SH OPTIONS

.TP
.BI --merge-all
Do a raw merge of all files.

.TP
.BI --unresolved-ok
Leave unresolved references unchanged and don't complain about them.

.TP
.BI --dereference
Resolve all references to their definitions

.TP
.BI --overlay
Overlay (merge) referenced content when dereferencing instead of
replacing the entire object

.TP
.BI --pretty
Format JSON output for human consumption

.TP
.BI --quiet
Don't produce output
