#!/usr/bin/python
#
# Participant list generator for 'idle' task spec
#
# Input is a test spec, assumed to have been validated by spec-is-valid.
#
# Output is a list of hostnames or IPs that are participating.
#

import pscheduler
import sys

json = pscheduler.json_load(exit_on_error=True)

null_reason = None

source = json.get('source', None)
if source is None:
    null_reason = "No source specified"

dest = json.get('dest', None)

#lead is whomever should be running the client. None is localhost
flip = json.get('flip', False)
if flip:
    participants = [ dest ]
else:
    participants = [ source ]



result = { "participants": participants }
if null_reason is not None:
    result["null-reason"] = null_reason

pscheduler.succeed_json(result)

