#!/usr/bin/python
#
# Participant list generator for 'idle' task spec
#
# Input is a test spec, assumed to have been validated by spec-is-valid.
#
# Output is a list of hostnames or IPs that are participating.
#

import pscheduler
import sys

json = pscheduler.json_load(exit_on_error=True)

#participant depends on mode
if json.get('single-participant-mode', False):
    #lead participant only participant
    result = [ None ]
else:
    #source first participant, dest the second
    source = None
    dest = None
    if 'source' in json:
        source = json['source']
        
    if 'dest' in json:
        dest = json['dest']
        
    result = [ source, dest ]

pscheduler.json_dump(result, sys.stdout )
pscheduler.succeed()
