#!/usr/bin/env python3
#
# Convert a test specification to command-line options

import pscheduler

from validate import check_spec_semantics

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True, semantics=check_spec_semantics)


# With a valid spec in hand, we can simply spit out the values one at
# a time.

result = []

for key, value in spec.items():

    # Things that get special handling

    if key == "schema":
        continue

    option = "--%s" % key

    if isinstance(value, bool):
        if value:
            result.append(option)
            continue
        continue

    result.append(option)

    if key == "data-ports":
        result.append("%d-%d" % (value['lower'], value['upper']))
        continue

    result.append(str(value))

pscheduler.succeed_json(result)
