#!/usr/bin/python
#
# Run a test.  Just the test spec is provided on stdin.
#

from pscheduler import psurl
import datetime
import json
import sys
import time

import pscheduler

# from stdin
input = pscheduler.json_load(exit_on_error=True)

try:
    url = input['test']['spec']['url']

except KeyError:
    pscheduler.fail('Missing data in input')

timeout_iso = input['test']['spec'].get("timeout", "PT2S")
timeout = pscheduler.timedelta_as_seconds(pscheduler.iso8601_as_timedelta(timeout_iso))
# timeout = timeout * len(input['test']['spec']['oidargs']) + 2

# Perform the test


start_time = datetime.datetime.now()
try:
    result = psurl.url_get(url, json=False)
    succeeded = True
    statusCode = result[0]
    htmlOutput = result[1]
except pscheduler.psurl.URLException:
    succeeded = False
    statusCode = "" 

end_time = datetime.datetime.now()



#
# Produce results
#

results = {
    'succeeded': succeeded,
    'result': {
        'schema': 1,
        'time': pscheduler.timedelta_as_iso8601( end_time - start_time ),
        'succeeded' : succeeded,
        'error': statusCode,
    },
}

pscheduler.succeed_json(results)

