#!/usr/bin/env python3

#
# Development Order #5:
# 
# This file will convert a test specification to command-line options.
#
# This can be tested directly using the following syntax:
# ./cli-to-spec --option argument | ./spec-to-cli

import pscheduler

spec = pscheduler.json_load(exit_on_error=True)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[

        # Add all argument strings here, as tuples

        ( 'host', 'host' ),
        ( 'host-node', 'host-node' ),
        ( 'timeout', 'timeout' ),
        ( 'duration', 'duration'),
        ( 'access-key', 'access-key' ),
	( 'bucket', 'bucket'),
	( 'secret-key', 'secret-key'),
	( 'url', 'url'),
	( 'iterations', 'iterations'),
	( 'object-size', 'object-size')
        ])

pscheduler.succeed_json(result)
