#!/usr/bin/env python3

#
# Development Order #4:
#
# Determine the duration of a specified test.
#

import math
import datetime
import pscheduler

json = pscheduler.json_load(exit_on_error=True)['spec']

timeout_iso = json.get("timeout", 'PT10S')
timeout = pscheduler.iso8601_as_timedelta(timeout_iso)

timeout += datetime.timedelta(seconds=1)

pscheduler.succeed_json({
    "duration": pscheduler.timedelta_as_iso8601( timeout )
    })
