#!/usr/bin/python
#
# Determine if this tool can run a test based on a test spec.
#

import pscheduler

json = pscheduler.json_load(exit_on_error=True)

try:
    if json['type'] != 'latencybg':
        pscheduler.succeed_json({
            "can-run": False,
            "reasons": [ "Unsupported test type" ]
        })
except KeyError:
    pscheduler.succeed_json({
        "can-run": False,
        "reasons": [ "Missing test type" ]
    })


pscheduler.succeed_json({ "can-run": True })
