#!/usr/bin/python
#
# Determine if this tool can run a test based on a test spec.
#

import datetime
import sys

import pscheduler

json = pscheduler.json_load(exit_on_error=True)

try:
    if json['type'] != 'latencybg':
        pscheduler.fail('Unsupported test type')
except KeyError:
    pscheduler.fail('Missing test type')


pscheduler.succeed()
