#!/usr/bin/python
#
# Determine the duration of powstream

import datetime
import sys

import pscheduler

from powstream_defaults import *

json = pscheduler.json_load(exit_on_error=True)

print json.get('duration', DEFAULT_DURATION)

pscheduler.succeed()
