#!/usr/bin/python
#
# Determine the duration of powstream

import pscheduler

from powstream_defaults import DEFAULT_DURATION

json = pscheduler.json_load(exit_on_error=True)

print json.get('duration', DEFAULT_DURATION)

pscheduler.succeed()
