#!/usr/bin/python
#
# Determine if this tool can run a test based on a test spec.
#

import datetime
import sys

import pscheduler

json = pscheduler.json_load(exit_on_error=True)

try:
    if json['type'] != 'throughput':
        pscheduler.fail('Unsupported test type')

    if json.has_key('bandwidth') and not json.has_key('udp'):
        pscheduler.fail('iperf cannot run TCP tests with throttled bandwidth')

except KeyError:
    pscheduler.fail('Missing test type')

pscheduler.succeed()
