#!/usr/bin/python
#
# Determine the duration of the iperf

import datetime
import sys

import pscheduler

from iperf_defaults import *

json = pscheduler.json_load(exit_on_error=True)

duration = int(json.get('duration', DEFAULT_DURATION))

print 'PT%dS' % (duration + DEFAULT_FUDGE_FACTOR + DEFAULT_WAIT_SLEEP)

pscheduler.succeed()
