#!/usr/bin/python
#
# Run an iperf test
#

import datetime
import logging
import json
import pscheduler
import re
import tempfile
import shutil
import sys
import time
import iperf_parser
from iperf_defaults import *

# track when this run starts
start_time = datetime.datetime.now()

logger = pscheduler.Log(prefix='iperf', quiet=True)

logger.debug("starting iperf tool")

# parse JSON input
input = pscheduler.json_load(exit_on_error=True)

logger.debug("Input is %s" % input)

try:
    participant = input['participant']
    participant_data = input['participant-data']
    test_spec = input['test']['spec']
    duration = pscheduler.iso8601_as_timedelta(input['schedule']['duration'])
except KeyError as e:
    pscheduler.fail("Missing required key in run input: %s" % e)
except:
    pscheduler.fail("Error parsing run input: %s" % sys.exc_info()[0])


def run_client():    
    time.sleep(DEFAULT_WAIT_SLEEP) #wait for server to boot

    iperf_args = ['/usr/bin/iperf']


    logger.debug(participant)
    logger.debug(participant_data)

    # who to connect to
    iperf_args.append('-c')
    iperf_args.append(test_spec['receiver'])

    # duration
    iperf_args.append('-t')
    iperf_args.append(test_spec['duration'])

    if test_spec.has_key('interval'):
        iperf_args.append('-i')
        iperf_args.append(test_spec['interval'])

    logger.info("Running command: %s" % " ".join(iperf_args))

    try:
        status, stdout, stderr = pscheduler.run_program(iperf_args)
    except Exception as e:
        logger.error("iperf failed to complete execution: %s" % e)
        pscheduler.fail("The iperf command failed during execution. See server logs for more details.")
    
    #see if command completed successfully
    logger.debug("iperf returned status %d" % status)

    if status:
        iperf_error = ''
        for line in stderr:
            iperf_error += line.rstrip().lstrip() + " "
        pscheduler.fail("iperf returned an error: %s" %iperf_error)

    logger.debug("Stdout = %s" % stdout)
    logger.debug("Stderr = %s" % stderr)

    lines = stdout.split("\n")    

    logger.debug("Lines are %s " % lines)

    seen_header = False

    results = iperf_parser.parse_output(lines)
    results['diag'] = stdout

    return results

def run_server():

    #init command
    iperf_args = ['/usr/bin/iperf', '-s' ]
    
    logger.info("Running command: %s" % " ".join(iperf_args))

    try:
        status, stdout, stderr = pscheduler.run_program(iperf_args,
                                                        timeout = pscheduler.timedelta_as_seconds(duration - (datetime.datetime.now() - start_time)),
                                                        timeout_ok = True)
    except Exception as e:
        logger.error("iperf failed to complete execution: %s" % e);
        pscheduler.fail("The iperf command failed during execution. See server logs for more details.")
    
    #check if server failed
    if status:
        iperf_error = ''
        for line in stderr:
            iperf_error += line.rstrip().lstrip() + " "
        pscheduler.fail("iperf returned an error: %s" % iperf_error)
    
    #log stdout in debug mode
    for line in stdout:
        logger.debug(line)
          
    return {"succeeded": True}



#determine whether we are the client or server mode for iperf
results = {}
try:
    if participant == 0:
        results = run_client()
    elif participant == 1:
        results = run_server()
    else:
        pscheduler.fail("Invalid participant.")
except Exception as e:
    logger.error("Exception %s" % e);

logger.info("Results: %s" % results)

pscheduler.succeed_json(results)
