#!/bin/sh -e

PKG=$(basename $(pwd)) 
PKG=${PKG%-*} # remove version
PKG=${PKG#*-} # remove prefix
CLASS=${PKG%%-*}
NAME=${PKG#*-}

TEST=$(basename $0)
INPUT=$PWD/debian/tests/$TEST.input
EXPECT=$PWD/debian/tests/$TEST.expect
OUTPUT=$AUTOPKGTEST_TMP/$TEST.output

[ -f $INPUT ] || INPUT=/dev/null
CMD=/usr/lib/pscheduler/classes/$CLASS/$NAME/$TEST
$CMD < $INPUT > $OUTPUT

if [ -s $EXPECT ] && ! grep -C 20 -f $EXPECT $OUTPUT
then
  cat $OUTPUT
  exit 3
fi
