#!/usr/bin/env python3
#
# Convert a test specification to command-line options

import pscheduler

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[
        ( 'duration', 'duration' ),
        ( 'host', 'host' ),
        ( 'interval', 'interval' ),
        ( 'starting-comment', 'starting-comment' ),
        ( 'parting-comment', 'parting-comment' ),
        ])

pscheduler.succeed_json(result)
