#!/bin/sh

exec cat << EOF
{
    "name": "idle",
    "description": "Consume time - NOT FOR PRODUCTION",
    "version": "1.0",
    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "perfsonar-developer@internet2.edu",
	"href": "http://www.perfsonar.net"
    },

    "scheduling-class": "normal"
}
EOF
