#!/bin/sh

# TODO: This can only handle linear arguments.  Tests that might have
# lists of things or recursive, complex structures won't work.  Those
# would have to be command-line only, which may not be so bad.

exec cat << EOF
[
    {
        "name": "starting_comment",
	"display": "Starting Comment",
	"description": "Something that goes to standard output when the test starts",
	"required": false,
	"_": "TODO: Need validation information"
    },
    {
        "name": "parting_comment",
	"display": "Parting Comment",
	"description": "Something that goes to standard output when the test ends",
	"required": false,
	"_": "TODO: Need validation information"
    },
]
EOF
