#!/usr/bin/python
#
# Participant list generator for 'idle' task spec
#
# Input is a test spec, assumed to have been validated by spec-is-valid.
#
# Output is a list of hostnames or IPs that are participating.
#

import pscheduler

from validate import spec_is_valid


json = pscheduler.json_load(exit_on_error=True)

valid, message = spec_is_valid(json)

if not valid:
    pscheduler.fail(message)


# This is a one-participant test, always the local system (null).
print '[ null ]'

pscheduler.succeed()
