#!/usr/bin/python
#
# Participant list generator for 'idle' task spec
#
# Input is a test spec, assumed to have been validated by spec-is-valid.
#
# Output is a list of hostnames or IPs that are participating.
#

import pscheduler

from validate import spec_is_valid


json = pscheduler.json_load(exit_on_error=True)

valid, message = spec_is_valid(json)

if not valid:
    pscheduler.fail(message)

try:
    pscheduler.succeed_json([json["host"]])
except KeyError:
    # Default is the local host.
    pscheduler.succeed_json([None])
