#!/bin/bash
#
# NOTE: This uses BASH arrays.
# TODO: Try and find a way to be POSIX sh compatible
#
# rpm-with-deps - Run RPM and install dependencies on failure.
#
# See the manual page for documentation.
#

TMPBASE=${TMP:=/tmp}/$(basename $0).$$

cleanup()
{
    rm -rf $TMPBASE*
}
trap cleanup EXIT

PROGRAM=$(echo $(basename $0) | sed -e 's/-.*$//')

RPM_ARGS=("$@")

# Try once, exiting if all went well.

"${PROGRAM}" "${RPM_ARGS[@]}" 2>$TMPBASE.first
STATUS=$?
[ "${STATUS}" -eq 0 ] && exit 0


# Figure out what packages were missing

fgrep 'is needed by' $TMPBASE.first \
    | awk '{ print $1 }' \
    > $TMPBASE.missing


# After this point, it's safe to die if something fails.
set -e


# If the build barfed and there were no packages missing, it's a
# legitimate error.

if [ "${STATUS}" -eq 0 -a ! -s $TMPBASE.missing ]
then
    cat $TMPBASE.first 1>&2
    exit $STATUS
fi

# Install anything that was missing.  YUM has a nasty habit of not
# treating uninstallable packages as being a problem, so the RPM that
# follows will have to die for its sins.

< $TMPBASE.missing xargs -r yum -y --color=never install 

# Do this manually because exec doesn't count as an exit.
cleanup

exec "${PROGRAM}" "${RPM_ARGS[@]}"
