.\" rpm-with-deps man page
.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.de Id
.ds Dt \\$4
..
.TH RPM-WITH-DEPS 1
.SH NAME
rpm-with-deps \- Run RPM, installing any dependent packages on failure
.SH SYNOPSIS
.B rpm-with-deps
.I [ ARGS ]

.SH DESCRIPTION
.PP
.B rpm-with-deps
front-ends
.IR rpm (8)
and intercepts errors caused by missing dependencies.  The errors are
used to install the missing packages using YUM, after which the run of
.IR rpm (8)
is attempted again.

.SH SEE ALSO
.IR rpm (8),
.IR yum (8)
