#!/usr/bin/env python3
#
# Evaluator for 'dot1x' task limits
#

import pscheduler

pscheduler.succeed_json({
    "passes": False,
    "errors": [ "Test limit specifications are no longer supported." ]
})
