#!/usr/bin/env python3
#
# Run a test.  Just the test spec is provided on stdin.
#

import datetime
import json
import sys
import time

import pscheduler

log = pscheduler.Log(prefix="tool-passthrough", quiet=True)

input = pscheduler.json_load(exit_on_error=True);

try:
    data = input['test']['spec']['data']
except KeyError:
    pscheduler.fail('Unable to find data in input')

# Don't bother sleeping here; there's no reason to wait.

# Perform the test

pscheduler.succeed_json({
    'succeeded': True,
    'diags': '',
    'error': '',
    'result': data
})
