#!/usr/bin/python
#
# Validator for 'trace' task spec
#

import pscheduler

from validate import spec_is_valid


try:
    json = pscheduler.json_load()
except ValueError as ex:
    pscheduler.succeed_json({
        "valid": False,
        "error": str(ex)
    })

valid, message = spec_is_valid(json)

result = {
    "valid": valid
}

if not valid:
    result["error"] = message

pscheduler.succeed_json(result)
