#!/bin/sh

exec cat << EOF
{
    "name": "idleex",
    "description": "Consume time exclusively - NOT FOR PRODUCTION",
    "version": "0.0",
    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "info@perfsonar.net",
	"href": "http://www.perfsonar.net"
    },

    "scheduling-class": "exclusive"
}
EOF
