#!/usr/bin/env python3

#
# Development Order #4:
#
# Determine the duration of a specified test.
#

#
# TODO: This is a bare-bones, unreliable implementation that should be
# used only for testing.
#

import datetime

import pscheduler

json = pscheduler.json_load(exit_on_error=True);


pscheduler.succeed_json({
    "duration": "PT5S"
    })
