#!/bin/sh


exec cat << EOF
{
    "name": "throughput",
    "description": "Tests designed primarily to active measure network throughput between a set of hosts",
    "version": "0.0",
    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "perfsonar-developer@internet2.edu",
	"href": "http://www.perfsonar.net"
    },
    "scheduling-class": "exclusive"
}
EOF
