#!/usr/bin/python
#
# Participant list generator for 'throughput' task spec
#
# Input is a test spec, assumed to have been validated by spec-is-valid.
#
# Output is a list of hostnames or IPs that are participating.
#

import pscheduler
import sys

json = pscheduler.json_load(exit_on_error=True)

#sender first participant, receiver the second
try:
    sender = json['sender']
except KeyError:
    pscheduler.fail('No sender in test specification')
    
try:
    receiver = json['receiver']
except KeyError:
    pscheduler.fail('No receiver in test specification')

result = [ sender, receiver ]

pscheduler.json_dump(result, sys.stdout )
pscheduler.succeed()
