#!/usr/bin/python
#
# Participant list generator for 'throughput' task spec
#
# Input is a test spec, assumed to have been validated by spec-is-valid.
#
# Output is a list of hostnames or IPs that are participating.
#

import pscheduler
import sys

json = pscheduler.json_load(exit_on_error=True)

#sender first participant, receiver the second
try:
    source = json['source']
except KeyError:
    source = None

try: 
    destination = json['destination']
except KeyError:
    pscheduler.fail("Missing destination argument in spec")
    
pscheduler.succeed_json( [ source, destination ] )

