#!/usr/bin/python
#
# Convert a test specification to command-line options

import pscheduler
import validate

spec = pscheduler.json_load(exit_on_error=True, max_schema=1)

if type(spec) != dict:
    pscheduler.fail("Invalid JSON for this operation")

valid, message = validate.spec_is_valid(spec)
if not valid:
    pscheduler.fail(message)

strings = []
bools = []

spec_properties = validate.SPEC_SCHEMA['properties']

for item in spec_properties.keys():
    if item == 'schema': continue
    if spec_properties[item].has_key("$ref") and "Boolean" in spec_properties[item]['$ref']:
        bools.append( (item, item) )
    else:
        strings.append( (item, item) )

result = pscheduler.speccli_build_args(spec, 
                                       strings=strings,
                                       bools=bools)
pscheduler.succeed_json(result)




