#!/usr/bin/python
#
# Convert a test specification to command-line options

import pscheduler

spec = pscheduler.json_load(exit_on_error=True)

if type(spec) != dict:
    pscheduler.fail("Invalid JSON for this operation")

result = []

try:
    result.append('--source')
    result.append(spec['source'])
except KeyError:
    pscheduler.fail("Missing source")
    
try:
    result.append('--destination')
    result.append(spec['destination'])
except KeyError:
    pscheduler.fail("Missing destination")

pscheduler.succeed_json(result)


