#!/usr/bin/env python3
#
# Validator for 'throughput' test spec
#

import pscheduler

from validate import spec_is_valid


try:
    json = pscheduler.json_load(max_schema=3)
    pscheduler.json_check_schema(json, 3)
except ValueError as ex:
    pscheduler.succeed_json({
        "valid": False,
        "error": str(ex)
    })

valid, message = spec_is_valid(json)

result = {
    "valid": valid
}

if not valid:
    result["error"] = message

pscheduler.succeed_json(result)
