#!/usr/bin/env python3
#
# Convert a test specification to command-line options

import pscheduler
import validate

spec = pscheduler.json_load(exit_on_error=True)

strings = []
bools = []

for key, value in spec.items():

    if key == 'schema':
        continue

    if isinstance(value, bool):
        bools.append((key, key))
    else:
        strings.append((key, key))

result = pscheduler.speccli_build_args(spec, 
                                       strings=strings,
                                       bools=bools)
pscheduler.succeed_json(result)




