#!/usr/bin/python
#
# Validator for 'owdelay' test spec
#

import pscheduler
import validate

json = pscheduler.json_load(exit_on_error=True)

# Run through all of the tags we expect to see, deleting the valid ones
valid, message = validate.spec_is_valid(json)

if not valid:
    pscheduler.fail(message)

pscheduler.succeed()
