#!/usr/bin/python
#
# Validator for 'throughput' test spec
#

import pscheduler
import validate

logger = pscheduler.Log(prefix='test-throughput')

json = pscheduler.json_load(exit_on_error=True)
logger.debug("Input to spec is valid: %s" % json)

valid, message = validate.spec_is_valid(json)

if not valid:
    pscheduler.fail(message)

pscheduler.succeed()
