#!/bin/sh

exec cat << EOF
{
    "name": "latencybg",
    "description": "Run one-way latency tests that can run at same time as other tests",
    "version": "0.0",
    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "info@perfsonar.net",
	"href": "http://www.perfsonar.net"
    },

    "scheduling-class": "background"
}
EOF
