#!/usr/bin/env python3
#
# Validator for 'latency' test spec
#

import pscheduler

def check_semantics(proposed):
    '''
    This checks that the spec is semantically-valid.  It is safe to
    assume that validation of the JSON passed.
    '''
    # Verify flip is not set if source not included.
    if 'source' not in proposed and proposed.get('flip', False):
        return(False, 'Flipped testing requires source and dest')

    return(True, 'OK')


pscheduler.plugin_spec_is_valid('test', semantic=check_semantics)
