#!/usr/bin/env python3
#
# Convert a test specification to command-line options

import pscheduler

from validate import check_spec_semantics

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True, semantic=check_spec_semantics)


#build command-line from schema
result = []
for key, value in spec.items():

    if key == "schema":
        continue

    option = "--%s" % key

    if isinstance(value, bool):
        if value:
            result.append(option)
        continue

    result.append(option)

    if key == 'data-ports':
        result.append("%d-%d" % (value['lower'], value['upper']))
        continue
    
    result.append(value)

pscheduler.succeed_json(result)
