#!/usr/bin/python3
#
# Return participant-specific data for a run
#

import pscheduler

json = pscheduler.json_load(exit_on_error=True)

# In this case, nothing of interest.
print("{}")

pscheduler.succeed()
