#!/bin/sh

set -e

ip link add autopkgtest type vrf table 10
ip link set dev autopkgtest up

ip link add name loop1 type dummy
ip link set dev loop1 master autopkgtest up

ip addr add 10.10.10.10/32 dev loop1
ip addr show

pscheduler task --context '{ "schema": 1, "contexts": [ [ { "context": "linuxvrf", "data": { "vrf": "autopkgtest" } } ] ] }' rtt --dest=10.10.10.10

ip link del loop1
ip link del autopkgtest
