#!/bin/sh
#
# Determine the duration of a specified test.
#

# Tracepath does a hardwaired maximum of 31 hops with a (guessed)
# timeout of 2 seconds.  Take that plus a couple of seconds to do DNS
# resolution and some buffer time.

echo 'PT1M10S'
exit 0
