#!/usr/bin/env python3
"""
Send a result to esmond
"""

import pscheduler

def archive(json):
    """Archive a single result."""
    return {
            "succeeded": False,
            "error": "Support for this tool has been discontinued."
        }
