#!/usr/bin/env python3
#
# Validate data for the esmond archiver
#

import pscheduler

pscheduler.succeed_json({
    "valid": False,
    "error": "Support for this tool has been discontinued."
    })
