#!/bin/sh -e
#
# Build all of the pScheduler RPMs and install them if running as
# root.
#

WHEREAMI=$(dirname "$0")

TMPBASE="${TMP:-/tmp}/${WHOAMI}.$$"
cleanup()
{
    rm -rf ${TMPBASE}*
}
trap cleanup EXIT


if [ "$(id -u)" = "0" ]
then
    INSTALL=install
fi

${WHEREAMI}/build-order > "${TMPBASE}.list"

for PACKAGE in $(cat "${TMPBASE}.list")
do
    cat <<EOF


#
# BUILDING ${PACKAGE}
#

EOF
    
    make -C "${PACKAGE}" clean build ${INSTALL}
done
