#!/bin/sh -e
#
# Build all of the pScheduler RPMs and install them if running as
# root.
#

WHEREAMI=$(dirname "$0")

TMPBASE="${TMP:-/tmp}/${WHOAMI}.$$"
cleanup()
{
    rm -rf ${TMPBASE}*
}
trap cleanup EXIT


. "${WHEREAMI}/os-info"

if [ "$1" = "--start-with" ]
then
    START_WITH=$2
    ${WHEREAMI}/build-order \
	| sed -n "/^${START_WITH}\$/,\$p" \
	> "${TMPBASE}.list"
else
    ${WHEREAMI}/build-order > "${TMPBASE}.list"
fi

FOUND_LIST="${TMPBASE}.found"

for PACKAGE in $(cat "${TMPBASE}.list")
do
    cat <<EOF


#
# BUILDING ${PACKAGE}
#

EOF

    case "${OSINFO_PACKAGING}" in

	rpm)
	    find "${PACKAGE}" -name "rpm" -type d > "${FOUND_LIST}"
	    if [ -s "${FOUND_LIST}" ]
	    then
		make -C "${PACKAGE}" clean build install
	    else
		echo "No RPM spec found.  Skipping."
	    fi
	    ;;
	
	deb)
	    find "${PACKAGE}" -name "debian" -type d > "${FOUND_LIST}"
	    if [ -s "${FOUND_LIST}" ]
	    then
		make -C "${PACKAGE}" clean build install
	    else
		echo "No debian directory found.  Skipping."
	    fi
	    ;;

	*)
	    echo "Can't buld for ${PACKAGE_FORMAT}" 1>&2
	    exit 1
	    ;;
    esac

done
