#!/bin/sh -e
#
# Preprocess the build order into something machine-usable
#
# Options:
#   --bundle b  Show packages in bundle b.  If b is "none," the output
#               will include only packages with no bundle specified.
#

WHEREAMI="$(dirname $0)"


# Gargle the arguments

BUNDLE=""

while echo "$1" | egrep -qe '^--.'
do
  OPTION="$1"
  shift

  case "$OPTION" in

      --bundle)
          BUNDLE="$1"
          shift
          ;;

      *)
          echo "Unknown option $OPTION" 1>&2
          exit 1
          ;;


  esac
done

bundle_filter()
{
    case "${BUNDLE}" in
	"")
	    cat
	    ;;
	none)
	    egrep -v -e '--bundle\s*[^\s]+'
	    ;;
	*)
	    fgrep -- "--bundle ${BUNDLE}"
	    ;;
    esac
}

m4 \
    "-DLSB_VENDOR=${LSB_VENDOR}" \
    "-DLSB_RELEASE=${LSB_RELEASE}" \
    "-DLSB_RELEASE_MAJOR=${LSB_RELEASE_MAJOR}" \
    "-DLSB_FAMILY=${LSB_FAMILY}" \
    "-DPACKAGE_FORMAT=${PACKAGE_FORMAT}" \
    "-DOS=${LSB_VENDOR}-${LSB_RELEASE_MAJOR}" \
    "-DOS_FAMILY=${LSB_FAMILY}-${LSB_RELEASE_MAJOR}" \
    $WHEREAMI/PACKAGE-BUILD-ORDER.m4 \
    | sed -e 's/#.*$//' \
    | egrep -ve '^\s*$' \
    | bundle_filter \
    | awk '{ print $1 }'
