#!/bin/sh -e
#
# Clean all of the pScheduler source directories
#

WHEREAMI=$(dirname "$0")

# Cleaning requires that make-generic-rpm be installed.
if ! rpm --quiet -q make-generic-rpm
then
    make -C "${WHEREAMI}/../make-generic-rpm" clean build install
fi


for PACKAGE in $(sed -e 's/#.*$//; /^\s*$/d' "${WHEREAMI}/RPM-BUILD-ORDER")
do
    make -C "${PACKAGE}" clean
done
