#!/bin/sh -e
#
# Run script for Dockerized pScheduler
#

# Start all services needed for pScheduler
service rsyslog start
service postgresql-9.5 start
service httpd start
service pscheduler-archiver start
service pscheduler-runner start
service pscheduler-scheduler start
service pscheduler-ticker start

# Do nothing so the container never exits.
while true
do
    sleep 3600
done
