#!/bin/sh -e
#
# Do an uninstall for all packages in reverse build order
#

WHEREAMI=$(dirname "$0")

for DIR in $( ${WHEREAMI}/build-order \
    | awk '{ print NR, $0 }' \
    | sort -rn \
    | cut -d ' ' -f 2- )
do
    make -C "${DIR}" uninstall
done
