#!/bin/sh -e
#
# Remove all of the pScheduler RPMs
# root.
#

WHEREAMI=$(dirname "$0")

if [ "${USER}" != "root" ]
then
    echo "Must be root." 1>&2
    exit 1
fi

for PACKAGE in $(sed -e 's/#.*$//; /^\s*$/d' "${WHEREAMI}/RPM-BUILD-ORDER" \
    | awk '{ print NR, $0 }' | sort -rn | cut -d ' ' -f 2-)
do
    printf "Removing ${PACKAGE}..."
    # Don't care if these fail, just get rid of them.
    if rpm --quiet -q ${PACKAGE}
    then
	rpm -e ${PACKAGE} || true
	echo "  Done."
    else
	echo "  Not installed."
    fi
done
