#!/bin/sh -e

# 
# Runs pylint against everything and dumps
# the output to stdout
#
# This is ultimately intended to be used for
# the jenkins builds but can be used by hand
# as well
#

WHEREAMI=$(dirname "$0")

PYLINT_ARGS="--rcfile=${WHEREAMI}/pylint.cfg"

# make sure we grab the pscheduler path
LIB_PATH="${WHEREAMI}/../python-pscheduler/pscheduler/"

which pylint >/dev/null || (echo "pylint doesn't appear to be installed" && exit 1);

for FILE in $( \
    find "${WHEREAMI}/.." -type f \
    | xargs file -i -F';' \
    | awk -F';' '$2 == "text/x-python" || $1 ~ /\.py$/ { print $1 }' \
    )
do

    echo "FILE = $FILE"
    PYLINT_FILENAME="pylint_$( \
	echo ${FILE} \
	| sed -e "s|^${WHEREAMI}/\.\./||g" \
	| tr '/.' '__'
	)"
    PYTHONPATH="${LIB_PATH}:${WHEREAMI}" pylint ${PYLINT_ARGS} "${FILE}" \
	| tee "pylint_${PYLINT_FILENAME}.log"
done
