#!/bin/sh -e
#
# Script to prep a system for pScheduler build/test
#
# System should be CentOS 6.x in the "Basic Server" configuration.
#
# NOTE: You'll need to bring eth0 up manually and adjust its ifcfg
# script so ONBOOT is yes before running this so you'll have a way to
# get the script onto the system.
#

# Un-comment these and configure to taste.
#NEW_USER=mfeit
#NEW_NAME="Mark Feit"
#NEW_UID=1838
#NEW_PASS="${NEW_USER}"


# No user-serviceable parts beyond this point.

# -----------------------------------------------------------------------------

if [ "${NEW_USER}" ]
then
    mount /dev/sr0 /mnt && true
    if [ ! -x '/mnt/VBoxLinuxAdditions.run' ]
    then
	echo "VirtualBox Guest Additions CD is not mounted." 1>&2
	exit 1
    fi

fi


# Determine the RHEL version without depending on lsb_release.
REDHAT_RELEASE=$(sed -e 's/^.* \([0-9.]\+\) .*$/\1/' /etc/redhat-release)
REDHAT_RELEASE_MAJOR=$(echo ${REDHAT_RELEASE} | awk -F. '{ print $1 }')
REDHAT_RELEASE_MAJOR_MINOR=$(echo ${REDHAT_RELEASE} | awk -F. '{ print $1 "." $2 }')


# Bring everything up to date
yum -y upgrade


# PostgreSQL
rpm -Uvh --force "https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-${REDHAT_RELEASE_MAJOR_MINOR}-$(uname -m)/pgdg-redhat95-9.5-2.noarch.rpm"

# Needed for documentation, which isn't RPM-ified yet and can't load
# this automatically.

# TODO: CentOS 6 installed enough of TeXLive to build the
# documentation.  Installing texlive-* is very heavy; see if it can be
# trimmed down.

yum -y install \
    texlive-\*



# Conveniences
yum -y install \
    emacs-nox \
    git \
    ntp \
    screen \
    tcsh \
    tree \


#
# Guest additions.  Only needed for convenience on VBox
#
# Make sure the guest additions ISO is attached before doing this.
#
#

if [ "${NEW_USER}" ]
then

    case "${REDHAT_RELEASE_MAJOR}" in
	6)
	    KERNEL_DEVEL=kernel-devel-$(uname -r)
	    ;;
	7)
	    yum -y install "https://dl.fedoraproject.org/pub/epel/epel-release-latest-${REDHAT_RELEASE_MAJOR}.noarch.rpm"
	    KERNEL_DEVEL="kernel-devel dkms"
	    ;;
    esac

    yum -y install bzip2 gcc ${KERNEL_DEVEL}

    # This exits 1 when XOrg isn't installed, even if successful
    /mnt/VBoxLinuxAdditions.run && true
    umount /mnt

    useradd -u "${NEW_UID}" -c "${NEW_NAME}" "${NEW_USER}"
    chsh -s /bin/tcsh "${NEW_USER}"
    echo "${NEW_PASS}" | passwd --stdin "${NEW_USER}"

    # Arrange for the user's home directory to be mounted.  CentOS 7
    # goes into emergency mode if the device can't be mounted
    # immediately at boot, so make this noauto and make rc.local do
    # it.

    USER_HOME=$(su - "${NEW_USER}" -c 'echo $HOME')

    cat >> /etc/fstab <<EOF
${NEW_USER}                ${USER_HOME}          vboxsf  noauto,uid=${NEW_UID}        0 0
EOF

    mount "${USER_HOME}"

    echo "mount '${USER_HOME}'" >> /etc/rc.local
    chmod +x /etc/rc.local

fi
