#!/usr/bin/env python3
#
# Return participant-specific data for a run
#

import packaging.version
import pscheduler
import sys
import ethr_utils

from ethr_defaults import *

json = pscheduler.json_load(exit_on_error=True)
result = {
    'schema': 3
}


try:
    participant = json['participant']
except KeyError:
    pscheduler.fail('Missing participant')

config = ethr_utils.get_config()

if participant == 0:    

    pass

elif participant == 1:

    # Server's listening port
    result['server_port'] = config['server_port']

else:

    pscheduler.fail('Invalid participant number for this test')


pscheduler.succeed_json(result)
