#!/usr/bin/python
#
# Run a test.  Just the test spec is provided on stdin.
#

import datetime
import json
import sys
import time

import pscheduler

input = pscheduler.json_load();

# Validate the input

# TODO: This should probably be in a module that can be shared with
# can-run.

# TODO: Be more thorough.

try:
    duration_iso = input['schedule']['duration']
except KeyError:
    pscheduler.fail('Unable to find duration in input')


duration = pscheduler.iso8601_as_timedelta(duration_iso)
if duration is None:
    pscheduler.fail_other(2, "Missing or invalid duration " + duration_iso)
else:
    if duration < datetime.timedelta(seconds=5):
        pscheduler.fail("Won't sleep for such a short time.")


# Perform the test

# The output is just mocked up.
output = ''

try:
    output += input['test']['spec']['starting_comment'] + '\n'
except KeyError:
    null

time.sleep(pscheduler.timedelta_as_seconds(duration))

try:
    output += input['test']['spec']['parting_comment'] + '\n'
except KeyError:
    null



#
# Produce results
#

results = {
    'succeeded': True,
    'diags': output,
    'error': '',
    'result': { 'time_slept': pscheduler.timedelta_as_iso8601(duration) }
}

pscheduler.succeed_json(results)
