#!/usr/bin/python
#
# Determine if this tool can run a test based on a test spec.
#

import datetime
import sys

import pscheduler

logger = pscheduler.Log(prefix='tool-bwctltraceroute', quiet=True)

json = pscheduler.json_load(exit_on_error=True);

# TODO: Should be checking the package schema and the task spec schema.
# TODO: Should be validating.

try:
    if json['type'] != 'trace':
        pscheduler.fail('Unsupported test type')
except KeyError:
    pscheduler.fail('Missing test type')


spec = json['spec']

errors = []

unsupported_options = [ 'algorithm', 'as', 'dest-port', 'fragment', 'probe-type', 'queries', 'sendwait', 'wait', 'sendwait' ]
for unsupported_option in unsupported_options:
    if spec.has_key(unsupported_option):
        pscheduler.fail("BWCTL does not support %s" % unsupported_option)


source = spec.get("source", "localhost")

if pscheduler.api_has_pscheduler(source):
    pscheduler.fail("Source has pscheduler, no need for BWCTL")

if not pscheduler.api_has_bwctl(source):
    logger.debug("No BWCTL at source")
    pscheduler.fail("No BWCTL on %s" % source)

logger.debug("can-run succeeded") 
pscheduler.succeed()

