#!/bin/bash -e
#
# Dump the names and version numbers of installed pScheduler packages
#

if [ -e /etc/debian_version ]; then
    dpkg-query -W 'pscheduler-*' \
        | awk '{sub("[^0-9.].*", "", $2); printf "%-40s %s\n", $1, $2}'
else
    rpm -qa --queryformat '%-40{NAME}%{VERSION}\n' \
        | egrep -e '^pscheduler-' \
        | sort
fi
