#!/usr/bin/env python3
#
# Participant list generator for 'rtt' test spec
#

import pscheduler
import sys

json = pscheduler.plugin_spec_is_valid('test', return_if_valid=True)

null_reason = None

source = json.get('source-node', json.get('source', None))
if source is None:
    null_reason = "No source specified"

result = { "participants": [ source ] }
if null_reason is not None:
    result["null-reason"] = null_reason

pscheduler.succeed_json(result)
