#!/usr/bin/env python3
#
# Format a spec
#

import sys
import pscheduler

from validate import spec_is_valid
from validate import MAX_SCHEMA

try:
    FMT = sys.argv[1]
except IndexError:
    FMT = 'text/plain'

json_in = pscheduler.json_load(exit_on_error=True, max_schema=MAX_SCHEMA)

valid, message = spec_is_valid(json_in)
if not valid:
    pscheduler.fail(message)

json = pscheduler.json_strip_hyphens(json_in)

json['_format'] = 'text/plain'

# NB: Hyphens have been stripped out of key names.

TEMPLATE='''
{% if _format == 'text/plain' %}

Destination ... {{ unspec(dest) }}
Source ........ {{ unspec(source) }}
Source Node ... {{ unspec(sourcenode) }}
Timeout ....... {{ unspec(timeout) }}

{% elif _format == 'text/html' %}

<table>
<tr><td>Destination</td><td>{{ unspec(dest) }}</td></tr>
<tr><td>Source</td><td>{{ unspec(source) }}</td></tr>
<tr><td>Source Node</td><td>{{ unspec(sourcenode) }}</td></tr>
<tr><td>Timeout</td><td>{{ unspec(timeout) }}</td></tr>
</table>

{% else %}

{{ error('Unsupported format "' + _format + '"') }}

{% endif %}
'''

try:
    print(pscheduler.jinja2_format(TEMPLATE, json, strip=True))
except RuntimeError as ex:
    pscheduler.fail(str(ex))
