#!/usr/bin/env python3
#
# Convert a test specification to command-line options

import pscheduler

json = pscheduler.plugin_spec_is_valid('test', return_if_valid=True)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[
        # Strings
        ( 'host', 'host' ),
        ( 'host-node', 'host-node' ),
        ( 'nameserver', 'nameserver' ),
        ( 'record', 'record' ),
        ( 'query', 'query' ),
        ( 'timeout', 'timeout' ),
        ])


pscheduler.succeed_json(result)
