#!/usr/bin/python
"""
DESCRIPTION
"""

import sys
import pscheduler

MAX_SCHEMA = 1

def archive(json):
    #Do archiving here


    #TODO: Add more descriptive comments

    return {'succeeded': True}




PARSER = pscheduler.RFC7464Parser(sys.stdin)
EMITTER = pscheduler.RFC7464Emitter(sys.stdout)

for parsed in PARSER:
    EMITTER(archive(parsed))

pscheduler.succeed()
