#!/usr/bin/env python3
#
# Convert a test specification to command-line options
#

import pscheduler

spec = pscheduler.plugin_spec_is_valid('test', return_if_valid=True)

result = pscheduler.speccli_build_args(spec, 
                                       strings=[
                                           ( 'host', 'host' ),
                                           ( 'host-node', 'host-node' ),
                                           ( 'ip-version', 'ip-version' ),
                                           ( 'timeout', 'timeout' ),
                                           ( 'url', 'url' ),
                                           ( 'parse', 'parse' ),
                                           ( 'keep-content', 'keep-content')
                                       ],
                                       bools=[
                                           ( 'always-succeed', 'always-succeed'),
                                       ]
                                   )

for header in spec.get('headers', {}).items():
    (name, value) = header
    result.append('--header')
    result.append('%s: %s' % (name, value))

pscheduler.succeed_json(result)
