#!/bin/sh

set -e

amqp-declare-queue -q test

pscheduler task --archive '{ "archiver": "rabbitmq", "data": { "_url": "amqp://localhost:5672", "routing-key": "test", "exchange": "" } }' rtt --dest=localhost

amqp-get -q test
