#!/usr/bin/env python3

#
# Development Order #4:
# 
# This file encodes CLI arguments as JSON data in a test spec,
# as defined by the datatypes in validate.py
# 
# This can be tested directly using the following syntax:
# ./cli-to-spec --option argument
#

import re
import argparse
import pscheduler
import sys

if len(sys.argv) > 1:

   # Args are on the command line
   args = sys.argv[1:]

else:

   # Args are in a JSON array on stdin
   json_args = pscheduler.json_load(exit_on_error=True)
   args = []

   if not isinstance(json_args,list):
      pscheduler.fail("Invalid JSON for this operation")
   for arg in json_args:
      if not ( isinstance(arg, str)
               or isinstance(arg, int)
               or isinstance(arg, float) ):
         pscheduler.fail("Invalid JSON for this operation")
   args = [ str(arg) for arg in json_args ]



# Gargle the arguments

arg_parser = argparse.ArgumentParser(epilog=
"""
    This test validates DNS64 IPv4 and IPv6 conversion
"""
)

# Add all potential command line options here


arg_parser.add_argument("query",
                      help="Hostname to look up.")

arg_parser.add_argument("--nameserver",
                      help="Nameserver to query.",
                        dest="nameserver")

arg_parser.add_argument("--host",
                      help="Host to run the test.", dest="host")

arg_parser.add_argument("--host-node",
                      help="Hostname to run the test.", dest="host_node")

arg_parser.add_argument("--translation-prefix",
                      help="Translation prefix to expect for converted results.",
                      dest="translation_prefix")

arg_parser.add_argument("--timeout",
                      help="Timeout for each query attempt",
                      dest="timeout")


arguments = arg_parser.parse_args()


# Call .set(n) on this object to indicate that a parameter requires
# schema level n or higher.  The object will return the highest-set
# value when .value() is called.
#
# For example, if the 'foo' parameter was introduced in schema level 2:
#
#  if options.foo is not None:
#      result['foo'] = options.foo
#      schema.set(2)
#
# If this is a brand-new test, you won't need to call .set() since the
# default is 1.

schema = pscheduler.HighInteger(1)


# Build the test specification.  All we do here is build and set
# schema levels.  Validation happens elsewhere.

result = { }

if arguments.query is not None:
   result['query'] = arguments.query

if arguments.nameserver is not None:
   result['nameserver'] = arguments.nameserver

if arguments.host is not None:
   result['host'] = arguments.host

if arguments.host_node is not None:
   result['host-node'] = arguments.host_node

if arguments.translation_prefix is not None:
   result['translation-prefix'] = arguments.translation_prefix

if arguments.timeout is not None:
   result['timeout'] = arguments.timeout

result['schema'] = schema.value()

pscheduler.succeed_json(result)
