#!/bin/sh

exec cat << EOF
{
    "name": "idlebg",
    "description": "Consume time in the background - NOT FOR PRODUCTION",
    "version": "0.0",
    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "perfsonar-developer@internet2.edu",
	"href": "http://www.perfsonar.net"
    },

    "scheduling-class": "background"
}
EOF
