#!/usr/bin/python
#
# Determine if this tool can run a test based on a test spec.
#

import datetime
import sys

import pscheduler

logger = pscheduler.Log(prefix='tool-iperf2', quiet=True)

json = pscheduler.json_load(exit_on_error=True)

if not json.get('type'):
    pscheduler.fail('Missing test type')

if json['type'] != 'throughput':
    pscheduler.fail('Unsupported test type')

if not json.get('spec'):
    pscheduler.fail('Missing test spec')

test_spec = json['spec']

supported_options = ["schema", "dest", "source",
                     "ip-version", "duration", "interval",
                     "parallel", "window-size", "mss", "bandwidth",
                     "buffer-length", "local-address", "congestion",
                     "udp"
                     ]

for option in test_spec.keys():
    if option not in supported_options:
        logger.debug("iperf2 unsupported option %s" % option)
        pscheduler.fail('iperf2 does not support %s option' % option)    


# bandwidth only supported in udp mode
if test_spec.has_key("bandwidth") and not test_spec.has_key("udp"):
    pscheduler.fail('iperf2 does not support specifying bandwidth on non-udp tests')

logger.debug("can-run succeeded")

pscheduler.succeed()
