#!/usr/bin/python
#
# Return participant-specific data for a run
#

import pscheduler
import random
import sys
import iperf2_utils
from iperf2_defaults import *

json = pscheduler.json_load(exit_on_error=True)
result = {}

try:
    participant = json['participant']
except KeyError:
    pscheduler.fail("Missing participant")

config = iperf2_utils.get_config()

if participant == 0:
    # Nothing interesing for participant 0
    pass
elif participant == 1:
    result["server_port"] = config["server_port"]
else:
    pscheduler.fail("Invalid participant number for this test")

pscheduler.succeed_json(result)
