#!/usr/bin/python
"""
Send a result to http.
"""

import sys
import pscheduler
import pscheduler.psurl

MAX_SCHEMA = 1

def archive(json):
    """Archive a single result."""

    schema = json["data"].get("schema", 1)
    if schema > MAX_SCHEMA:
        return {
            "succeeded": False,
            "error": "Unsupported schema version %d; max is %d" % (
                schema, MAX_SCHEMA)
        }

    errors = ()

    try:
        url = json['data']['_url']
    except KeyError:
        raise RuntimeError("Reached code that wasn't supposed to be reached.")

    try:
        op = json['data']['op']
    except KeyError:
        op = 'post'

    try:
        bind = json['data']['bind']
    except KeyError:
        bind = None

    if op == 'post':

        try:
            pscheduler.url_post( url, data=pscheduler.json_dump(json['result']), json=False, bind=bind )
        except Exception as ex:
            result = {
                "succeeded": False,
                "error": "Failed to log result: %s" % str(ex)
            }
            if "retry-policy" in json['data']:
                policy = pscheduler.RetryPolicy(json['data']['retry-policy'], iso8601=True)
                retry_time = policy.retry(json["attempts"])
                if retry_time is not None:
                    result["retry"] = retry_time
            return result

    elif op == 'put':

        try:
            pscheduler.url_put( url, data=pscheduler.json_dump(json['result']), json=False, bind=bind )
        except Exception as ex:
            result = {
                "succeeded": False,
                "error": "Failed to log result: %s" % str(ex)
            }
            if "retry-policy" in json['data']:
                policy = pscheduler.RetryPolicy(json['data']['retry-policy'], iso8601=True)
                retry_time = policy.retry(json["attempts"])
                if retry_time is not None:
                    result["retry"] = retry_time
            return result

    else:
        return {
            "succeeded": False,
            "error": "Invalid op arg: %s" % op
        }

    return {'succeeded': True}




PARSER = pscheduler.RFC7464Parser(sys.stdin)
EMITTER = pscheduler.RFC7464Emitter(sys.stdout)

for parsed in PARSER:
    EMITTER(archive(parsed))

pscheduler.succeed()
