#!/bin/sh

exec cat << EOF
{
    "name": "http",
    "description": "Send a raw JSON result to HTTP",
    "version": "1.0",

    "maintainer": {
        "name": "perfSONAR Development Team",
	"email": "perfsonar-developer@internet2.edu",
	"href": "http://www.perfsonar.net"
    }
}
EOF
