#!/usr/bin/python

#
# Development Order #5:
#
# This is the meat and bones of the tool, where the actual desired
# commands or operation will be run. The results are then recorded
# and added to the 'results' JSON data, which will then be sent
# back to the test. Both system and api are able to be used here.
#

import datetime
import json
import sys
import time

import pscheduler

# from stdin
input = pscheduler.json_load(exit_on_error=True)

# Take input from test spec
example = input['test']['spec']['example']

# Run the actual task here

if succeeded:
    # Gather results


# Organize results into json data
results = {
    'succeeded': succeeded,
    'result': {
        'schema': 1,
        'example': example
    },
    'error': error,
    'diags': diags
}

pscheduler.succeed_json(results)

