#!/usr/bin/python
#
# Run a test.  Just the test spec is provided on stdin.
#

import datetime
import json
import sys
import time

import pscheduler

# from stdin
input = pscheduler.json_load(exit_on_error=True)

# Take input from test spec
example = input['test']['spec']['example']

# Run the actual task here

if succeeded:
    # Gather results


# Organize results into json data
results = {
    'succeeded': succeeded,
    'result': {
        'schema': 1,
        'example': example
    },
    'error': error,
    'diags': diags
}

pscheduler.succeed_json(results)

